# Generated by Django 5.2.10 on 2026-01-16 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_historicaltask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskHistory',
        ),
    ]
