# Generated by Django 5.2.10 on 2026-01-22 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_historicaltask_delete_taskhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/', verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('image', 'Изображение'), ('document', 'Документ'), ('archive', 'Архив'), ('other', 'Другое')], max_length=20, verbose_name='Тип файла')),
                ('original_name', models.CharField(max_length=255, verbose_name='Оригинальное имя')),
                ('file_size', models.IntegerField(default=0, verbose_name='Размер файла (байт)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task', verbose_name='Задача')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Кто загрузил')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'db_table': 'tasks_attachment',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['task', 'file_type'], name='tasks_attac_task_id_aaa5c0_idx')],
            },
        ),
    ]
